title: Fire Learn
description: Learning site for FIRE!
exclude: [README.md]
include: [".well-known"]

# applies pretty for all
permalink: pretty
plugins:
  - jekyll-relative-links

repository: LearningToBurn/ltb-theme@v2.0.31
remote_theme: LearningToBurn/ltb-theme@v2.0.31

brand: napkin

learntrack: 
  url: https://learntrack-func.azurewebsites.net
  api_key: v636ne579hs489sx0xw5jyof
